services:
  postgresdb:
    user: ${PID}:${GID}
    image: postgres:17
    container_name: postgresdb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/postgress/data:/var/lib/postgresql/data
      - ./database/backups:/init

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatanime-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgresdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whatanime-frontend
    restart: unless-stopped
    ports:
      - 5173:5173
    depends_on:
      - backend